#!/bin/bash
U="team"
DIR="femmebabe"
cd $"/home/$U/$DIR/"
source venv/bin/activate
python generate_site.py
# Sub website backup
cd $"/home/$U/$DIR/web/site/"
sudo rm -r .git
git init --initial-branch=main
git add --all
git commit -m "website updates"
git remote add origin git@github.com:daisycamber/glamgirlx.git
git push -u -f origin main
sudo rm -r .git
